"""add_email_on_failure_column

Revision ID: f1d36396318b
Revises: 0004_connections_schedule
Create Date: 2026-07-02 09:04:54.209679

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f1d36396318b'
down_revision: Union[str, None] = '0004_connections_schedule'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workflows', sa.Column('email_on_failure', sa.Boolean(), nullable=True))
    op.execute("UPDATE workflows SET email_on_failure = FALSE")
    op.alter_column('workflows', 'email_on_failure', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workflows', 'email_on_failure')
    # ### end Alembic commands ###
